//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMGamerPart3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameScore
    {
        public int ScoreID { get; set; }
        public string GameID { get; set; }
        public string TeamID { get; set; }
        public string GameName { get; set; }
        public string Description { get; set; }
        public string TeamA { get; set; }
        public int TeamAScore { get; set; }
        public string TeamB { get; set; }
        public int TeamBScore { get; set; }
        public decimal Spectators { get; set; }
    }
}
