//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMGamerPart3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public string GameName { get; set; }
        public string GameType { get; set; }
        public string Description { get; set; }
        public int Spectators { get; set; }
        public string WinningTeam { get; set; }
        public int WinningTeamScore { get; set; }
        public string LosingTeam { get; set; }
        public int LosingTeamScore { get; set; }
        public System.DateTime GameDate { get; set; }
        public int AllowedTotalScore { get; set; }
    }
}
